version: '3'
services:
  db_mysql:
    image: mysql:8.0.2
    container_name: db_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laundry_shop
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: tran.tuan
      MYSQL_USER: hoanglam
      MYSQL_PASSWORD: trantuan
      SERVICE_NAME: mysql8
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      #- ./db_data/:/var/lib/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge